version: '3'

services:
  springboot:
    container_name: someup # ec2내에서 동작하는 컨테이너명
    image: junseoplee/someup:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : dev-env # 사용할 profile
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
