services:
  springboot:
    container_name: someup # ec2내에서 동작하는 컨테이너명
    image: someupsite/someup:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : dev-env # 사용할 profile
    networks:
      - my_network

  redis:
    image: redis
    container_name: redis-cache
    command: ["redis-server", "--port", "6379"] # 비밀번호 설정 제거
    ports:
      - 6379:6379
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
